language: python
os: linux
dist: bionic
arch: amd64

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - python3 test_database_utilities.py
  - python3 test_line_profiles.py
  - python3 test_tips.py
  - python3 test_hitran_html_parsers.py 
  - python3 test_hitran.py
